# Highed DataFrame Analysis

In [1]:
# import necessary libraries
import numpy             as np
import pandas            as pd
import matplotlib.pyplot as plt


# linear regression
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# elastic net
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn import linear_model as lm

# KNN regressor
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsRegressor

# Boosters
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor
import xgboost as xgb

# import necessary dataframes
highed = pd.read_pickle('highed_prepped.pkl')
urate  = pd.read_csv('urateFRED.csv')
lfrate = pd.read_csv('lfpFRED.csv')

In [2]:
# assign specific survey years based on sample ID
# (to be discussed later on)

suryr_map = {
    101: 1993,
    103: 1993,
    201: 1995,
    203: 1995,
    301: 1997,
    303: 1997,
    401: 1999,
    403: 1999,
    601: 2003,
    603: 2003,
    701: 2006,
    703: 2006,
    801: 2008,
    803: 2008,
    901: 2010,
    903: 2010,
    1001: 2013,
}

highed['suryr'] = highed['sample'].map(suryr_map)

In [3]:
urate.columns = [col.lower() for col in urate.columns]
urate.columns

Index(['date', 'unrate'], dtype='object')

In [4]:
urate['date'] = urate['date'].str[:4]
urate_by_year = urate.groupby('date').agg('mean')['unrate']
urate_by_year

date
1990    5.616667
1991    6.850000
1992    7.491667
1993    6.908333
1994    6.100000
1995    5.591667
1996    5.408333
1997    4.941667
1998    4.500000
1999    4.216667
2000    3.966667
2001    4.741667
2002    5.783333
2003    5.991667
2004    5.541667
2005    5.083333
2006    4.608333
2007    4.616667
2008    5.800000
2009    9.283333
2010    9.608333
2011    8.933333
2012    8.075000
2013    7.358333
2014    6.158333
2015    5.275000
2016    4.800000
Name: unrate, dtype: float64

In [5]:
urate_map = {
    1993: urate_by_year.iloc[3],
    1995: urate_by_year.iloc[5],
    1997: urate_by_year.iloc[7],
    1999: urate_by_year.iloc[9],
    2003: urate_by_year.iloc[13],
    2006: urate_by_year.iloc[16],
    2008: urate_by_year.iloc[18],
    2010: urate_by_year.iloc[20],
    2013: urate_by_year.iloc[23]
}

highed['urate'] = highed['suryr'].map(urate_map)

In [6]:
lfrate.columns = [col.lower() for col in lfrate.columns]
lfrate.columns

Index(['date', 'civpart', 'civpart_pch'], dtype='object')

In [7]:
lfrate['date'] = lfrate['date'].str[:4]
lfrate_by_year = lfrate.groupby('date').agg('mean')
lfrate_by_year.reset_index(inplace=True)
lfrate_by_year

    date    civpart  civpart_pch
0   1989  66.500000    -0.150150
1   1990  66.533333    -0.012382
2   1991  66.166667    -0.050182
3   1992  66.441667     0.038067
4   1993  66.300000     0.012740
5   1994  66.575000     0.037707
6   1995  66.625000    -0.037332
7   1996  66.766667     0.075132
8   1997  67.108333     0.024913
9   1998  67.083333     0.000074
10  1999  67.083333    -0.012346
11  2000  67.066667    -0.012290
12  2001  66.833333    -0.037032
13  2002  66.583333    -0.049863
14  2003  66.241667    -0.050258
15  2004  65.983333     0.000153
16  2005  66.033333     0.012722
17  2006  66.166667     0.050449
18  2007  66.033333    -0.050084
19  2008  66.025000    -0.025100
20  2009  65.400000    -0.153006
21  2010  64.708333    -0.038283
22  2011  64.108333    -0.038879
23  2012  63.700000    -0.038877
24  2013  63.258333    -0.104966
25  2014  62.883333    -0.013058
26  2015  62.658333    -0.013015
27  2016  62.700000     0.000000

In [8]:
lfrate_map = {
    1993: lfrate_by_year.iloc[4,1],
    1995: lfrate_by_year.iloc[6,1],
    1997: lfrate_by_year.iloc[8,1],
    1999: lfrate_by_year.iloc[10,1],
    2003: lfrate_by_year.iloc[14,1],
    2006: lfrate_by_year.iloc[17,1],
    2008: lfrate_by_year.iloc[19,1],
    2010: lfrate_by_year.iloc[21,1],
    2013: lfrate_by_year.iloc[24,1]
}

lfrate_pct_map = {
    1993: lfrate_by_year.iloc[4,2],
    1995: lfrate_by_year.iloc[6,2],
    1997: lfrate_by_year.iloc[8,2],
    1999: lfrate_by_year.iloc[10,2],
    2003: lfrate_by_year.iloc[14,2],
    2006: lfrate_by_year.iloc[17,2],
    2008: lfrate_by_year.iloc[19,2],
    2010: lfrate_by_year.iloc[21,2],
    2013: lfrate_by_year.iloc[24,2]
}

highed['lfp'] = highed['suryr'].map(lfrate_map)
highed['lfp_delta'] = highed['suryr'].map(lfrate_pct_map)
highed

                           weight  sample  age  biryr  gender  race  usctz  \
year personid
1993 10000000000000007   407.6917     101   33   1960       2     2      1
     10000000000000103    52.3937     101   48   1945       1     2      1
     10000000000000108   436.3180     101   28   1965       2     2      1
     10000000000000202   179.0664     101   33   1960       2     3      0
     10000000000000204   145.5788     101   28   1965       2     2      1
...                           ...     ...  ...    ...     ...   ...    ...
2013 140101080300000301   75.2450    1001   46   1965       2     2      1
     140101080300000409   25.6203    1001   56   1955       2     2      1
     140101080300000506  838.2060    1001   65   1945       2     2      1
     140101080300000702   35.7301    1001   27   1985       2     2      1
     140101080300000800  478.6435    1001   50   1960       1     2      1

                         bachfld  bachgrp  highdeg  ...  pringrp  emsec  \
year personid                                       ...
1993 10000000000000007    226395        2        2  ...        7      4
     10000000000000103    799995        7        2  ...        1      4
     10000000000000108    719995        7        1  ...        1      4
     10000000000000202    537260        5        2  ...        5      2
     10000000000000204    799995        7        2  ...        5      4
...                          ...      ...      ...  ...      ...    ...
2013 140101080300000301   226395        2        1  ...        2      4
     140101080300000409   567350        5        1  ...        5      4
     140101080300000506   459395        4        1  ...        5      4
     140101080300000702   587995        5        1  ...        5      4
     140101080300000800   611995        6        4  ...        7      4

                         wapri  waprsm  salary  cpi2009c  suryr     urate  \
year personid
1993 10000000000000007       2       1   31000     1.485   1993  6.908333
     10000000000000103       4       4   48000     1.485   1993  6.908333
     10000000000000108       5       1   30000     1.485   1993  6.908333
     10000000000000202       2       1   16000     1.485   1993  6.908333
     10000000000000204       2       1   41000     1.485   1993  6.908333
...                        ...     ...     ...       ...    ...       ...
2013 140101080300000301      4       1   66000     0.921   2013  7.358333
     140101080300000409     11       3  100000     0.921   2013  7.358333
     140101080300000506      5       1   52000     0.921   2013  7.358333
     140101080300000702      5       1   52000     0.921   2013  7.358333
     140101080300000800     10       5  150000     0.921   2013  7.358333

                               lfp  lfp_delta
year personid
1993 10000000000000007   66.300000   0.012740
     10000000000000103   66.300000   0.012740
     10000000000000108   66.300000   0.012740
     10000000000000202   66.300000   0.012740
     10000000000000204   66.300000   0.012740
...                            ...        ...
2013 140101080300000301  63.258333  -0.104966
     140101080300000409  63.258333  -0.104966
     140101080300000506  63.258333  -0.104966
     140101080300000702  63.258333  -0.104966
     140101080300000800  63.258333  -0.104966

[535631 rows x 24 columns]

---

# Analysis for Under 30s

In [9]:
highed_young = highed[highed['age'].isin(range(20,31))]
highed_young

                           weight  sample  age  biryr  gender  race  usctz  \
year personid
1993 10000000000000108   436.3180     101   28   1965       2     2      1
     10000000000000204   145.5788     101   28   1965       2     2      1
     10000000000010204    72.4603     101   28   1965       1     2      1
     10000000000020707    69.6265     101   28   1965       2     2      1
     10000000000060403   436.3180     101   28   1965       2     2      1
...                           ...     ...  ...    ...     ...   ...    ...
2013 140101080209080001   57.8556    1001   27   1985       1     1      1
     140101080209080403   28.4980    1001   29   1980       1     2      1
     140101080209080500   90.0814    1001   28   1985       2     2      1
     140101080209080706  172.6619    1001   27   1985       2     2      1
     140101080300000702   35.7301    1001   27   1985       2     2      1

                         bachfld  bachgrp  highdeg  ...  pringrp  emsec  \
year personid                                       ...
1993 10000000000000108    719995        7        1  ...        1      4
     10000000000000204    799995        7        2  ...        5      4
     10000000000010204    198895        1        1  ...        1      4
     10000000000020707    547280        5        1  ...        5      4
     10000000000060403    799995        7        1  ...        5      4
...                          ...      ...      ...  ...      ...    ...
2013 140101080209080001   226395        2        1  ...        2      3
     140101080209080403   699995        6        1  ...        6      4
     140101080209080500   537260        5        1  ...        5      4
     140101080209080706   587995        5        1  ...        5      4
     140101080300000702   587995        5        1  ...        5      4

                         wapri  waprsm  salary  cpi2009c  suryr     urate  \
year personid
1993 10000000000000108       5       1   30000     1.485   1993  6.908333
     10000000000000204       2       1   41000     1.485   1993  6.908333
     10000000000010204       2       1   44000     1.485   1993  6.908333
     10000000000020707       6       1   38000     1.485   1993  6.908333
     10000000000060403      14       5   19000     1.485   1993  6.908333
...                        ...     ...     ...       ...    ...       ...
2013 140101080209080001      2       1   25000     0.921   2013  7.358333
     140101080209080403      8       3   60000     0.921   2013  7.358333
     140101080209080500      5       1   47000     0.921   2013  7.358333
     140101080209080706     12       3   57000     0.921   2013  7.358333
     140101080300000702      5       1   52000     0.921   2013  7.358333

                               lfp  lfp_delta
year personid
1993 10000000000000108   66.300000   0.012740
     10000000000000204   66.300000   0.012740
     10000000000010204   66.300000   0.012740
     10000000000020707   66.300000   0.012740
     10000000000060403   66.300000   0.012740
...                            ...        ...
2013 140101080209080001  63.258333  -0.104966
     140101080209080403  63.258333  -0.104966
     140101080209080500  63.258333  -0.104966
     140101080209080706  63.258333  -0.104966
     140101080300000702  63.258333  -0.104966

[128715 rows x 24 columns]

In [10]:
### DATA IN 2009 DOLLARS

highed_young['gender'] = np.where(highed_young['gender'] == 2, 0, 1)
highed_young['asian'] = np.where(highed_young['race'] == 1, 1, 0)
highed_young['minority'] = np.where(highed_young['race'] != 2, 1, 0)
highed_young['high_mast'] = np.where(highed_young['highdeg'] == 2, 1, 0)
highed_young['high_phdd'] = np.where(highed_young['highdeg'] == 3, 1, 0)
highed_young['high_prof'] = np.where(highed_young['highdeg'] == 4, 1, 0)
highed_young['bach_csci'] = np.where(highed_young['bachfld'].isin([198895]), 1, 0)
highed_young['bach_ssci'] = np.where(highed_young['bachfld'].isin([429295,438995,449995,459395,489395]), 1, 0)
highed_young['bach_econ'] = np.where(highed_young['bachfld'].isin([419295]), 1, 0)
highed_young['bach_scnc'] = np.where(highed_young['bachfld'].isin([318730,338785,338795,398895]), 1, 0)
highed_young['bach_engr'] = np.where(highed_young['bachfld'].isin([527250,537260,547280,567350,587995,699995]), 1, 0)
highed_young['bach_mgmt'] = np.where(highed_young['bachfld'].isin([719995]), 1, 0)
highed_young['ocedrlp'] = np.where(highed_young['ocedrlp'] == 3, 0,
                                  np.where(highed_young['ocedrlp'] == 2, 1, 2))
highed_young['income_2009'] = highed_young['salary'] * highed_young['cpi2009c']

<ipython-input-10-8e5767f8e534>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['gender'] = np.where(highed_young['gender'] == 2, 0, 1)
<ipython-input-10-8e5767f8e534>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['asian'] = np.where(highed_young['race'] == 1, 1, 0)
<ipython-input-10-8e5767f8e534>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['minority'] = np.where(highed_young['race'] != 2, 1, 0)
<ipython-input-10-8e5767f8e534>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['high_mast'] = np.where(highed_young['highdeg'] == 2, 1, 0)
<ipython-input-10-8e5767f8e534>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['high_phdd'] = np.where(highed_young['highdeg'] == 3, 1, 0)
<ipython-input-10-8e5767f8e534>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['high_prof'] = np.where(highed_young['highdeg'] == 4, 1, 0)
<ipython-input-10-8e5767f8e534>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['bach_csci'] = np.where(highed_young['bachfld'].isin([198895]), 1, 0)
<ipython-input-10-8e5767f8e534>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['bach_ssci'] = np.where(highed_young['bachfld'].isin([429295,438995,449995,459395,489395]), 1, 0)
<ipython-input-10-8e5767f8e534>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['bach_econ'] = np.where(highed_young['bachfld'].isin([419295]), 1, 0)
<ipython-input-10-8e5767f8e534>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['bach_scnc'] = np.where(highed_young['bachfld'].isin([318730,338785,338795,398895]), 1, 0)
<ipython-input-10-8e5767f8e534>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['bach_engr'] = np.where(highed_young['bachfld'].isin([527250,537260,547280,567350,587995,699995]), 1, 0)
<ipython-input-10-8e5767f8e534>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['bach_mgmt'] = np.where(highed_young['bachfld'].isin([719995]), 1, 0)
<ipython-input-10-8e5767f8e534>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['ocedrlp'] = np.where(highed_young['ocedrlp'] == 3, 0,
<ipython-input-10-8e5767f8e534>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highed_young['income_2009'] = highed_young['salary'] * highed_young['cpi2009c']

In [11]:
highed_young.reset_index(inplace=True)
highed_young.drop(columns=['race', 'bachfld', 'bachgrp', 'highdeg', 'degfld', 'deggrp', 'wapri', 'waprsm'], inplace=True)
highed_young.drop(columns=['sample', 'suryr', 'prinjob', 'pringrp', 'emsec', 'personid'], inplace=True)
highed_young

/Users/lucasnelson/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py:4305: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,year,weight,age,biryr,gender,usctz,ocedrlp,salary,cpi2009c,urate,...,high_mast,high_phdd,high_prof,bach_csci,bach_ssci,bach_econ,bach_scnc,bach_engr,bach_mgmt,income_2009
0,1993,436.3180,28,1965,0,1,2,30000,1.485,6.908333,...,0,0,0,0,0,0,0,0,1,44550.0
1,1993,145.5788,28,1965,0,1,2,41000,1.485,6.908333,...,1,0,0,0,0,0,0,0,0,60885.0
2,1993,72.4603,28,1965,1,1,2,44000,1.485,6.908333,...,0,0,0,1,0,0,0,0,0,65340.0
3,1993,69.6265,28,1965,0,1,1,38000,1.485,6.908333,...,0,0,0,0,0,0,0,1,0,56430.0
4,1993,436.3180,28,1965,0,1,0,19000,1.485,6.908333,...,0,0,0,0,0,0,0,0,0,28215.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128710,2013,57.8556,27,1985,1,1,1,25000,0.921,7.358333,...,0,0,0,0,0,0,0,0,0,23025.0
128711,2013,28.4980,29,1980,1,1,2,60000,0.921,7.358333,...,0,0,0,0,0,0,0,1,0,55260.0
128712,2013,90.0814,28,1985,0,1,2,47000,0.921,7.358333,...,0,0,0,0,0,0,0,1,0,43287.0
128713,2013,172.6619,27,1985,0,1,1,57000,0.921,7.358333,...,0,0,0,0,0,0,0,1,0,52497.0
128714,2013,35.7301,27,1985,0,1,2,52000,0.921,7.358333,...,0,0,0,0,0,0,0,1,0,47892.0

In [12]:
y = np.sqrt(highed_young['income_2009'])
x = highed_young.drop(columns=['income_2009', 'salary', 'cpi2009c', 'age', 'weight', 'year', 'biryr'])
x.sort_index(axis='columns', inplace=True)

x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=2/3,
                                                    random_state=490)

x_train_std = x_train.apply(lambda x: (x - np.mean(x))/np.std(x), axis = 0)
x_test_std  = x_test.apply(lambda x: (x - np.mean(x))/np.std(x), axis = 0)

x_train_std = sm.add_constant(x_train_std)
x_test_std  = sm.add_constant(x_test_std)
x_train     = sm.add_constant(x_train)
x_test      = sm.add_constant(x_test)

### Elastic Net

In [13]:
# fit = sm.OLS(y_train, x_train)

In [14]:
# param_grid = {'alpha': 10.**np.arange(-5, -1, 1), 
#               'l1_ratio': np.arange(0, 1, 0.1)}

# cv_enet = lm.ElasticNet(fit_intercept = False, normalize = False,
#                         random_state = 490)
# grid_search = GridSearchCV(cv_enet, param_grid, cv = 5,
#                          scoring = 'neg_root_mean_squared_error',
#                           n_jobs = -1)
# grid_search.fit(x_train_std, y_train)
# best = grid_search.best_params_
# best

In [15]:
# ols_model = sm.OLS(y_train, x_train_std)
# ols_result = ols_model.fit()
# fit_enet = ols_model.fit_regularized(alpha = best['alpha'], L1_wt = best['l1_ratio'])
# final = sm.regression.linear_model.OLSResults(ols_model, 
#                                               fit_enet.params,
#                                               ols_result.normalized_cov_params)

# print(final.summary2())

### statsmodel.api

In [16]:
# fit_sm = sm.OLS(y_train, x_train).fit()
# print(fit_sm.summary2())

##### Predicting

In [17]:
# # y_hat_sm = fit_sm.predict(x_test)
# rmse_enet = np.sqrt(np.mean(  (y_test - fit_enet.predict(x_test_std))**2  ))
# rmse_null = np.sqrt(np.mean(  (y_test - np.mean(y_train))**2  ))
# print(rmse_enet)
# print(round((rmse_enet-rmse_null)/rmse_null*100, 4))

---

## Boosting

#### AdaBooster

In [14]:
rmse_null = rmse(np.mean(y_train), y_test)
rmse_null

-1.780730007894249e-09
3539.2258748513923

In [15]:
reg_ada = AdaBoostRegressor(base_estimator = DecisionTreeRegressor(max_depth = 1),
                 n_estimators = 200,
                 learning_rate = 0.5)
reg_ada.fit(x_train, y_train)

AdaBoostRegressor(base_estimator=DecisionTreeRegressor(max_depth=1),
                  learning_rate=0.5, n_estimators=200)

In [16]:
rmse_ada = rmse(reg_ada.predict(x_test), y_test)
rmse_ada

56.989209027936546

In [17]:
%%time

param_grid = {
    'n_estimators': [15, 25, 50, 75],
    'learning_rate': 10.**np.arange(-6, -2),
}

ada_cv = AdaBoostRegressor(base_estimator = DecisionTreeRegressor(max_depth = 1),
                          random_state=490)

grid_search = GridSearchCV(ada_cv, param_grid,
                          cv = 5,
                          scoring = 'r2',
                          n_jobs = -1).fit(x_train, y_train)

best = grid_search.best_params_
best

CPU times: user 8.17 s, sys: 922 ms, total: 9.1 s
Wall time: 3min

{'learning_rate': 1e-06, 'n_estimators': 75}

In [18]:
reg_ada = AdaBoostRegressor(base_estimator = DecisionTreeRegressor(max_depth = 1),
                            random_state=490,
                            n_estimators = best['n_estimators'],
                            learning_rate = best['learning_rate'])

reg_ada.fit(x_train, y_train)

rmse_ada = rmse(reg_ada.predict(x_test), y_test)
rmse_ada

56.75993591760683

#### Gradient Boosting

In [19]:
reg_gb = GradientBoostingRegressor(n_estimators = 200,
                                  max_depth = 2,
                                  learning_rate = 0.1,
                                  validation_fraction = 1/8,
                                  n_iter_no_change = 4,
                                  verbose = 2)

reg_gb.fit(x_train, y_train)

      Iter       Train Loss   Remaining Time
         1        3471.8893           18.59s
         2        3405.0319           20.51s
         3        3348.7770           19.60s
         4        3302.1055           18.47s
         5        3262.6758           17.63s
         6        3228.8265           16.89s
         7        3195.4914           16.28s
         8        3169.8499           16.25s
         9        3144.8773           15.92s
        10        3124.4771           15.45s
        11        3105.8585           15.04s
        12        3090.3064           15.08s
        13        3075.7982           15.03s
        14        3062.9423           14.81s
        15        3049.8812           14.67s
        16        3038.5981           14.63s
        17        3028.1987           14.47s
        18        3018.9215           14.41s
        19        3009.8709           14.28s
        20        3001.6058           14.22s
        21        2993.9121           14.47s
        22        2986.4044           14.36s
        23        2979.9523           14.23s
        24        2973.7168           14.07s
        25        2967.0734           13.89s
        26        2961.6939           13.70s
        27        2956.5081           13.66s
        28        2951.3410           13.52s
        29        2946.9477           13.37s
        30        2942.2313           13.27s
        31        2938.1071           13.12s
        32        2933.7754           12.97s
        33        2929.7570           12.83s
        34        2924.4677           12.81s
        35        2921.1104           12.73s
        36        2918.1313           12.63s
        37        2915.0877           12.59s
        38        2910.7218           12.48s
        39        2908.0283           12.39s
        40        2903.9356           12.30s
        41        2901.0250           12.26s
        42        2898.5206           12.22s
        43        2895.6722           12.28s
        44        2893.2910           12.21s
        45        2891.2001           12.14s
        46        2889.2985           12.08s
        47        2885.8914           11.99s
        48        2883.7223           11.93s
        49        2881.7675           11.88s
        50        2880.0358           11.80s
        51        2878.3855           11.69s
        52        2876.2684           11.58s
        53        2874.6611           11.48s
        54        2871.8149           11.37s
        55        2870.2751           11.28s
        56        2868.9259           11.18s
        57        2867.6181           11.07s
        58        2866.0126           10.97s
        59        2863.6627           10.86s
        60        2862.3894           10.77s
        61        2861.2637           10.67s
        62        2859.3421           10.56s
        63        2857.6997           10.46s
        64        2856.6037           10.37s
        65        2855.0264           10.26s
        66        2853.7742           10.16s
        67        2852.0309           10.08s
        68        2850.9843           10.01s
        69        2850.0560            9.94s
        70        2849.1611            9.91s
        71        2847.7945            9.81s
        72        2846.5424            9.74s
        73        2845.1538            9.67s
        74        2843.8202            9.60s
        75        2842.9285            9.53s
        76        2841.6151            9.46s
        77        2840.8629            9.40s
        78        2840.1288            9.34s
        79        2838.9592            9.25s
        80        2837.3250            9.19s
        81        2836.5614            9.11s
        82        2835.7981            9.05s
        83        2834.6714            8.97s
        84        2834.0313            8.88s
        85        2833.4429            8.79s
        86        2832.4907            8.72s
        87        2831.7580            8.62s
        88        2831.1013            8.56s
        89        2830.2037            8.50s
        90        2829.5652            8.42s
        91        2829.0516            8.36s
        92        2828.1446            8.28s
        93        2827.6410            8.21s
        94        2826.8772            8.12s
        95        2826.3675            8.05s
        96        2825.4542            7.97s
        97        2824.9217            7.88s
        98        2823.7386            7.79s
        99        2823.3237            7.70s
       100        2822.8981            7.62s
       101        2822.1821            7.53s
       102        2821.7329            7.44s
       103        2820.7495            7.36s
       104        2820.3282            7.27s
       105        2819.9833            7.22s
       106        2819.4126            7.13s
       107        2818.8385            7.05s
       108        2818.4846            6.97s
       109        2817.8304            6.89s
       110        2817.4514            6.83s
       111        2817.0833            6.76s
       112        2816.6254            6.69s
       113        2816.1504            6.61s
       114        2815.8487            6.54s
       115        2815.5403            6.47s
       116        2815.2231            6.39s
       117        2814.8063            6.31s
       118        2814.4991            6.23s
       119        2813.9943            6.15s
       120        2813.7431            6.08s
       121        2813.4869            6.01s
       122        2813.2193            5.93s
       123        2812.4492            5.86s
       124        2812.0796            5.78s
       125        2811.7615            5.70s
       126        2811.5016            5.63s
       127        2811.2908            5.55s
       128        2811.0817            5.47s
       129        2810.7126            5.40s
       130        2810.2662            5.31s
       131        2809.9663            5.23s
       132        2809.5695            5.15s
       133        2809.3406            5.07s
       134        2808.9454            4.99s
       135        2808.7778            4.91s
       136        2808.4076            4.84s
       137        2808.2080            4.78s
       138        2808.0382            4.70s
       139        2807.6988            4.62s
       140        2807.5058            4.54s
       141        2807.2796            4.47s
       142        2807.1269            4.39s
       143        2806.8197            4.31s
       144        2806.6453            4.23s
       145        2806.3911            4.15s
       146        2806.1225            4.07s
       147        2805.9795            3.99s
       148        2805.8082            3.92s
       149        2805.5073            3.84s
       150        2805.2455            3.76s
       151        2805.1214            3.68s
       152        2804.9767            3.60s
       153        2804.7716            3.53s
       154        2804.5527            3.45s
       155        2804.4249            3.38s
       156        2804.2699            3.30s
       157        2804.1393            3.22s
       158        2803.9102            3.14s
       159        2803.3055            3.07s
       160        2803.1995            2.99s
       161        2803.0221            2.92s
       162        2802.7359            2.85s
       163        2802.3706            2.77s
       164        2802.2704            2.70s
       165        2802.1366            2.63s
       166        2802.0267            2.55s
       167        2801.7912            2.48s
       168        2801.5619            2.40s
       169        2801.4762            2.33s
       170        2801.3244            2.25s
       171        2801.0427            2.18s
       172        2800.9540            2.10s
       173        2800.7559            2.02s
       174        2800.6589            1.95s
       175        2800.4449            1.87s
       176        2800.3286            1.80s
       177        2800.2613            1.72s
       178        2800.0746            1.65s
       179        2799.8478            1.57s
       180        2799.7729            1.50s
       181        2799.6887            1.42s
       182        2799.5691            1.34s
       183        2799.4658            1.27s
       184        2799.2978            1.19s
       185        2799.0975            1.12s

       186        2798.9379            1.04s
       187        2798.7726            0.97s
       188        2798.7145            0.89s
       189        2798.6448            0.82s
       190        2798.5484            0.74s
       191        2798.4121            0.67s
       192        2798.2792            0.59s
       193        2798.2134            0.52s
       194        2798.1645            0.44s
       195        2798.1019            0.37s
       196        2797.9873            0.30s
       197        2797.9024            0.22s
       198        2797.8455            0.15s
       199        2797.7197            0.07s
       200        2797.6768            0.00s

GradientBoostingRegressor(max_depth=2, n_estimators=200, n_iter_no_change=4,
                          validation_fraction=0.125, verbose=2)

In [25]:
from sklearn.metrics import mean_squared_error

rms_gb = mean_squared_error(y_test, reg_gb.predict(x_test), squared=True)
rms_gb

2790.151995591478

#### Extreme Gradient Boosting

In [21]:
x_train_train, x_train_test, y_train_train, y_train_test = train_test_split(x_train, y_train,
                                                                            train_size = 4/5,
                                                                            random_state = 490)

In [22]:
reg_xgb = xgb.XGBRegressor(n_estimators = 200,
                          max_depth = 2,
                          learning_rate = 0.1,
                          random_state = 490)

reg_xgb.fit(x_train_train, y_train_train,
           eval_set = [(x_train_test, y_train_test)],
           early_stopping_rounds = 4)

[0]	validation_0-rmse:193.97310
[1]	validation_0-rmse:176.26325
[2]	validation_0-rmse:160.49913
[3]	validation_0-rmse:146.46492
[4]	validation_0-rmse:134.02322
[5]	validation_0-rmse:123.02195
[6]	validation_0-rmse:113.27793
[7]	validation_0-rmse:104.73705
[8]	validation_0-rmse:97.27106
[9]	validation_0-rmse:90.71945
[10]	validation_0-rmse:85.03958
[11]	validation_0-rmse:80.14595
[12]	validation_0-rmse:75.93383
[13]	validation_0-rmse:72.33123
[14]	validation_0-rmse:69.26791
[15]	validation_0-rmse:66.65652
[16]	validation_0-rmse:64.45917
[17]	validation_0-rmse:62.62433
[18]	validation_0-rmse:61.07471
[19]	validation_0-rmse:59.78712
[20]	validation_0-rmse:58.70433
[21]	validation_0-rmse:57.79762
[22]	validation_0-rmse:57.05013
[23]	validation_0-rmse:56.42783
[24]	validation_0-rmse:55.90191
[25]	validation_0-rmse:55.47966
[26]	validation_0-rmse:55.11909
[27]	validation_0-rmse:54.80412
[28]	validation_0-rmse:54.55292
[29]	validation_0-rmse:54.33918
[30]	validation_0-rmse:54.16164
[31]	validation_0-rmse:54.01578
[32]	validation_0-rmse:53.88862
[33]	validation_0-rmse:53.78570
[34]	validation_0-rmse:53.70034
[35]	validation_0-rmse:53.61368
[36]	validation_0-rmse:53.54305
[37]	validation_0-rmse:53.48754
[38]	validation_0-rmse:53.43337
[39]	validation_0-rmse:53.38678
[40]	validation_0-rmse:53.32733
[41]	validation_0-rmse:53.28682
[42]	validation_0-rmse:53.25157
[43]	validation_0-rmse:53.22784
[44]	validation_0-rmse:53.19938
[45]	validation_0-rmse:53.17186
[46]	validation_0-rmse:53.12786
[47]	validation_0-rmse:53.10989
[48]	validation_0-rmse:53.09224
[49]	validation_0-rmse:53.06688
[50]	validation_0-rmse:53.02970
[51]	validation_0-rmse:53.01110
[52]	validation_0-rmse:52.99882
[53]	validation_0-rmse:52.98093
[54]	validation_0-rmse:52.96900
[55]	validation_0-rmse:52.95349
[56]	validation_0-rmse:52.92638
[57]	validation_0-rmse:52.91523
[58]	validation_0-rmse:52.89764
[59]	validation_0-rmse:52.87256
[60]	validation_0-rmse:52.86081
[61]	validation_0-rmse:52.85204
[62]	validation_0-rmse:52.82542
[63]	validation_0-rmse:52.81615
[64]	validation_0-rmse:52.79608
[65]	validation_0-rmse:52.78693
[66]	validation_0-rmse:52.78014
[67]	validation_0-rmse:52.77203
[68]	validation_0-rmse:52.76012
[69]	validation_0-rmse:52.74470
[70]	validation_0-rmse:52.72830
[71]	validation_0-rmse:52.71984
[72]	validation_0-rmse:52.71131
[73]	validation_0-rmse:52.70315
[74]	validation_0-rmse:52.69698
[75]	validation_0-rmse:52.68510
[76]	validation_0-rmse:52.67122
[77]	validation_0-rmse:52.66456
[78]	validation_0-rmse:52.65615
[79]	validation_0-rmse:52.64302
[80]	validation_0-rmse:52.63668
[81]	validation_0-rmse:52.62655
[82]	validation_0-rmse:52.62133
[83]	validation_0-rmse:52.60746
[84]	validation_0-rmse:52.59978
[85]	validation_0-rmse:52.59539
[86]	validation_0-rmse:52.58928
[87]	validation_0-rmse:52.58462
[88]	validation_0-rmse:52.57653
[89]	validation_0-rmse:52.57151
[90]	validation_0-rmse:52.56650
[91]	validation_0-rmse:52.55706
[92]	validation_0-rmse:52.54094
[93]	validation_0-rmse:52.53539
[94]	validation_0-rmse:52.52987
[95]	validation_0-rmse:52.51939
[96]	validation_0-rmse:52.51503
[97]	validation_0-rmse:52.51149
[98]	validation_0-rmse:52.50723
[99]	validation_0-rmse:52.49634
[100]	validation_0-rmse:52.49056
[101]	validation_0-rmse:52.48880
[102]	validation_0-rmse:52.48670
[103]	validation_0-rmse:52.48340
[104]	validation_0-rmse:52.47397
[105]	validation_0-rmse:52.47205
[106]	validation_0-rmse:52.45986
[107]	validation_0-rmse:52.45517
[108]	validation_0-rmse:52.45158
[109]	validation_0-rmse:52.44854
[110]	validation_0-rmse:52.44062
[111]	validation_0-rmse:52.43866
[112]	validation_0-rmse:52.43689
[113]	validation_0-rmse:52.43312
[114]	validation_0-rmse:52.43110
[115]	validation_0-rmse:52.42399
[116]	validation_0-rmse:52.41945
[117]	validation_0-rmse:52.41759
[118]	validation_0-rmse:52.41152
[119]	validation_0-rmse:52.40953
[120]	validation_0-rmse:52.40041
[121]	validation_0-rmse:52.39905
[122]	validation_0-rmse:52.39525
[123]	validation_0-rmse:52.39327
[124]	validation_0-rmse:52.38741
[125]	validation_0-rmse:52.38665
[126]	validation_0-rmse:52.38456
[127]	validation_0-rmse:52.38259
[128]	validation_0-rmse:52.37667
[129]	validation_0-rmse:52.37544
[130]	validation_0-rmse:52.37389
[131]	validation_0-rmse:52.36930
[132]	validation_0-rmse:52.36612
[133]	validation_0-rmse:52.36435
[134]	validation_0-rmse:52.35746
[135]	validation_0-rmse:52.35551
[136]	validation_0-rmse:52.35112
[137]	validation_0-rmse:52.34922
[138]	validation_0-rmse:52.34862
[139]	validation_0-rmse:52.34510
[140]	validation_0-rmse:52.34426
[141]	validation_0-rmse:52.34368
[142]	validation_0-rmse:52.34190
[143]	validation_0-rmse:52.33750
[144]	validation_0-rmse:52.33356
[145]	validation_0-rmse:52.33240
[146]	validation_0-rmse:52.33235
[147]	validation_0-rmse:52.33150
[148]	validation_0-rmse:52.32980
[149]	validation_0-rmse:52.32678
[150]	validation_0-rmse:52.32637
[151]	validation_0-rmse:52.32626
[152]	validation_0-rmse:52.32429
[153]	validation_0-rmse:52.32251
[154]	validation_0-rmse:52.32172
[155]	validation_0-rmse:52.32082
[156]	validation_0-rmse:52.31900
[157]	validation_0-rmse:52.31818
[158]	validation_0-rmse:52.31695
[159]	validation_0-rmse:52.31211
[160]	validation_0-rmse:52.31135
[161]	validation_0-rmse:52.30883
[162]	validation_0-rmse:52.30810
[163]	validation_0-rmse:52.30513
[164]	validation_0-rmse:52.30517
[165]	validation_0-rmse:52.30505
[166]	validation_0-rmse:52.30409
[167]	validation_0-rmse:52.30128
[168]	validation_0-rmse:52.29953
[169]	validation_0-rmse:52.29578
[170]	validation_0-rmse:52.29570
[171]	validation_0-rmse:52.29321
[172]	validation_0-rmse:52.29379
[173]	validation_0-rmse:52.29277
[174]	validation_0-rmse:52.28838
[175]	validation_0-rmse:52.28831
[176]	validation_0-rmse:52.28807
[177]	validation_0-rmse:52.28720
[178]	validation_0-rmse:52.28675
[179]	validation_0-rmse:52.28644
[180]	validation_0-rmse:52.28658
[181]	validation_0-rmse:52.28560
[182]	validation_0-rmse:52.28533
[183]	validation_0-rmse:52.28190
[184]	validation_0-rmse:52.28154
[185]	validation_0-rmse:52.28032
[186]	validation_0-rmse:52.27694
[187]	validation_0-rmse:52.27618
[188]	validation_0-rmse:52.27596
[189]	validation_0-rmse:52.27599
[190]	validation_0-rmse:52.27308
[191]	validation_0-rmse:52.27259
[192]	validation_0-rmse:52.27111
[193]	validation_0-rmse:52.26980
[194]	validation_0-rmse:52.26906
[195]	validation_0-rmse:52.26873
[196]	validation_0-rmse:52.26718
[197]	validation_0-rmse:52.26664
[198]	validation_0-rmse:52.26552
[199]	validation_0-rmse:52.26538

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=2,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=200, n_jobs=4, num_parallel_tree=1, random_state=490,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [26]:
rms_xgb = mean_squared_error(y_test, reg_xgb.predict(x_test), squared=True)
rms_xgb

2788.800799185251

In [28]:
print(rmse_ada ** 2)
print(rms_gb)
print(rms_xgb)

3221.690325370834
2790.151995591478
2788.800799185251

In [30]:
print(rmse_null ** 2)

3539.2258748513923

In [40]:
highed_young.to_pickle('highed_prepped_pickle.pkl')